cabal-version: 3.0
name:          pledge
version:       0.1.0.0

executable pledge-main
  hs-source-dirs:   .
  main-is:          Examples/Main.hs
  default-language: GHC2021
  ghc-options:      -Wno-missing-home-modules
  build-depends:
      base
    , containers
    , effectful
    , effectful-core
    , QuickCheck
    , sbv
  other-modules:
      Pledge
      Examples.UnitTest.PledgeTest
      Examples.UnitTest.PresburgerTest
      Examples.RE.Memory
      Examples.RE.FileHandle
      Examples.RE.Mutex
      Examples.RE.Transaction
      Examples.RE.CryptoSession
      Examples.RE.NetworkProtocol
      Examples.RE.Capability
      Examples.RE.Sensor
      Examples.RE.Shadow
      Examples.SL.HeapMemory
      Examples.SL.BankAccount
      Examples.SL.LinkedList

executable pledge-solver-test
  hs-source-dirs:   .
  main-is:          Examples/SL/SolverTest.hs
  default-language: GHC2021
  ghc-options:      -Wno-missing-home-modules
  build-depends:
      base
    , containers
    , sbv
  other-modules:
      Pledge
      Solver
